Update RMF codegen
commercetools/commercetools-docs-kit pull request #1094
Opened 2021-08-27 20:09 UTC by jenschude

2021-09-03 13:59 UTC, nkuehn approved these changes

2021-09-07 14:38 UTC, nkuehn requested changes

2021-09-07 14:38 UTC, nkuehn commented on packages/writing-style/styles/commercetools/Acronyms.yml
> +  - RMF # "Rest Modeling Framework"
Please remove this, the writing style is not for our own internal content but for user facing content.  In that context, "RMF" must be explained before use. 

@davifantasia  the root cause is that we are still validating release notes etc. with the writing style which does not make sense. 

Can be excluded with a special comment for now (or you remove "md" extensions from writing style checking right here)

2021-09-07 14:38 UTC, nkuehn commented on packages/writing-style/styles/commercetools/DateFormat.yml
> +  - '[^v]\d{1,2}(?:\.|\/)\d{1,2}(?:\.|\/)\d{2,4}'
This is a similar case but can stay since it catches a case that can happen e.g. in SDK documetnation too.

2021-09-09 09:29 UTC, nkuehn commented
@davifantasia  can you please help excluding MD files or generally files outside the websites directory from the writing style checks? Thanks !

2021-09-10 07:05 UTC, jenschude commented
> @davifantasia can you please help excluding MD files or generally files outside the websites directory from the writing style checks? Thanks !

The linting may be done independently in a separate PR to get this one here merged

2021-09-10 07:37 UTC, davifantasia approved these changes

2021-09-10 07:41 UTC, merged