[Design adjustments] Implement new design and separate data structure for the footer
commercetools/commercetools-docs-kit pull request #1826
Opened 2023-09-14 13:26 UTC by timonrey

closes #1774

2023-09-18 07:57 UTC, zbalek requested changes
Hi @timonrey 👋 The implementation looks good, but the spacing seems to be a little off. Somehow the spacing between the logo and the first column seems to be much smaller than the design one. I suggest to use a smaller [ct logo](https://brandfolder.com/commercetools/assets-1/#!asset/vn5r672hwtkmwwwqkptr6qw3) (size 60px) which would increase the space available to increase the spacing. This would also allow us to increase the spacing between the columns to ca 48px. Happy to jump on a call.

2023-09-18 12:59 UTC, zbalek approved these changes

2023-09-19 06:58 UTC, gabriele-ct approved these changes
👍

2023-09-19 07:18 UTC, timonrey commented
Blocked because it should go together with the mega menu into the next release
Mega menu PR: https://github.com/commercetools/commercetools-docs-kit/pull/1820

2023-10-09 09:43 UTC, merged