feat(theme): allow to optionally enable canonical urls
commercetools/commercetools-docs-kit pull request #531
Opened 2020-06-30 08:16 UTC by emmenko

Superseeds #525 
Closes #512

2020-06-30 12:42 UTC, emmenko commented
Yeah, I suppose the linkinator needs to be configured. Do you want to open an issue first? We can also contribute to the feature if it's deemed appropriate.

2020-07-01 07:27 UTC, nkuehn commented
> Do you want to open an issue first? We can also contribute to the feature if it's deemed appropriate.

I can ask whether we can sponsor something, but we can also try to directly contribute. The maintainer works at google so I guess it's not a sponsoring-driven model.  As opposed to the previous library we used the codebase looks pretty sane to me, so contributing would be nice. 


existing issues in the repo that matter to us:
 * https://github.com/JustinBeckwith/linkinator/issues/166  (CLI output without localhost, nice to have)
 * https://github.com/JustinBeckwith/linkinator/issues/79  (fragment identifier / anchor support, that's **pretty important** to us - in the current repo 99% of the link check failures are wrong fragment identifiers)

2020-07-01 07:39 UTC, nkuehn commented
PS: I opened an issue in the linkinator project:  https://github.com/JustinBeckwith/linkinator/issues/175

2020-07-01 07:40 UTC, nkuehn commented
PPS:  HTMLProofer has a fancy script documented that dynamically ignores new files but i find it insufficient:  https://github.com/gjtorikian/html-proofer#ignoring-new-files

2020-07-06 10:41 UTC, emmenko commented
Let's put this PR on hold / draft until we decide how to proceed.

cc @nkuehn

2020-07-07 11:07 UTC, nkuehn commented
@emmenko : @davifantasia  and me decided to try to contribute the necessary feature to linkinator.  If they are responsive we need to contribute more anyways (hash validation).

2020-09-18 09:23 UTC, davifantasia commented
@nkuehn @emmenko enabling canonical links works with the skip attribute. I believe we can now review and close this.

For the hash fragment validation I would open a different PR for that.

2020-09-18 11:33 UTC, nkuehn commented
> @nkuehn @emmenko enabling canonical links works with the skip attribute. I believe we can now review and close this.

Sorry, @davifantasia  - can you clarify what you mean with this?  getting a link checker that does not fail on these would require doing a change here to add the skip attribute but why close this PR altogether?

2020-09-18 13:40 UTC, nkuehn requested changes
Result of analysing the situation with @davifantasia :
 * we prefer to continue working with this plugin
 * that means we cannot add a custom skip attribute to the canonical link
 * that means in linkinator we don't need support for skip attributes but rather explicitly for canonical links
  * the linkinator exclusion of "docs.commercetools.com" is necessary evil now but needs to go away because we need it for e.g.  linking to custom apps docs.

2020-09-18 13:40 UTC, nkuehn commented on packages/gatsby-theme-docs/gatsby-config.js
> +          siteUrl: `https://${productionHostname}`,
```suggestion
          siteUrl: `https://${productionHostname}`,
          noTrailingSlash: true,
          noHash: true,
          noQueryString: true,
```
https://www.gatsbyjs.com/plugins/gatsby-plugin-react-helmet-canonical-urls/#how-to-use

Esp. for the release notes overview we must not have query strings in the URL.

2020-09-18 13:40 UTC, nkuehn commented on packages/gatsby-theme-docs/utils/default-options.js
> +  enableCanonicalUrls: false,
default should be true since it's a best practice to have canonical links

2020-09-22 20:30 UTC, nkuehn commented
@davifantasia  do you want to take over checking my feedback here - this is also needed for migration

2020-09-24 16:36 UTC, closed without merging