endpoint design implementation
commercetools/commercetools-docs-kit pull request #692
Opened 2020-10-01 15:52 UTC by davifantasia

Closes https://github.com/commercetools/commercetools-docs-kit/issues/684

2020-10-02 16:02 UTC, nkuehn commented on packages/gatsby-theme-api-docs/src/components/resource/method/url.js
> +            {uris.baseUri.replace(/^(https:\/\/)/, '')}
```suggestion
            {uris.baseUri}
```
that was omitted in the design, but one reason to give the hostname always its own line was to have the proper URL including protocol again

2020-10-06 11:42 UTC, emmenko approved these changes
Code and VRTs look good from my side 👌

2020-10-06 11:42 UTC, emmenko commented on packages/gatsby-theme-api-docs/src/components/resource/method/index.js
> +export default Method;
Usually you can simply write `export { default } from './method';`

2020-10-06 19:29 UTC, nkuehn requested changes
Compared to the visual design and found some differences:
 1. the text color of the hostname and the "OAuth2 Scopes", "Path Parameters" etc. headings is still the previous grey - the new design has them in darker to have enough contrast over the grey background, 
 2. the (red monospace) code blocks still have a background and border which is visible (esp. the border) if you look closely - and it add extra unneeded spacing.   When they are on the grey background they should have no background or border at all.
 3. It's not explicitly in the design, but I think the header row of the Response examples should have the darker grey defined under "White Table inside Endpoint" in the invision provided designs.  The two greys do not really contrast good enough.  (this might be annoying because it would be a third theme for the code examples next to dark and light - can be discussed).   I'll send sven the question.

2020-10-12 14:09 UTC, davifantasia commented
> 3. It's not explicitly in the design, but I think the header row of the Response examples should have the darker grey defined under "White Table inside Endpoint" in the invision provided designs.  The two greys do not really contrast good enough.  (this might be annoying because it would be a third theme for the code examples next to dark and light - can be discussed).   I'll send sven the question.

Created an issue for this here - https://github.com/commercetools/commercetools-docs-kit/issues/712

2020-10-13 08:53 UTC, nkuehn approved these changes
Good for now, the response example box header will get a different color in a separate step.

2020-10-13 08:55 UTC, merged