chore: add outline to string literals
commercetools/commercetools-docs-kit pull request #852
Opened 2021-01-28 19:23 UTC by TimonRey

closes #797

2021-01-29 07:50 UTC, Shecki requested changes
@TimonRey  it now looks like it has two outlines?
The old one should be replaced with the new color.

Also the corner-radius should be used from the old outline.

Thanks

2021-01-29 08:48 UTC, emmenko commented
@Shecki is this only relevant for inline code elements inside tables? Or in general?

2021-01-29 08:49 UTC, Shecki commented
@emmenko in gerneral

2021-01-29 09:11 UTC, emmenko commented
Ok

2021-01-29 09:12 UTC, emmenko requested changes

2021-01-29 09:12 UTC, emmenko commented on packages/ui-kit/src/components/markdown.js
> +  outline: 1px solid ${colors.light.borderSecondary};
You shouldn't change the `outline` style, but the border color instead.

2021-01-29 09:27 UTC, emmenko requested changes

2021-01-29 09:27 UTC, emmenko commented on packages/ui-kit/src/components/markdown.js
> +  border-color: ${colors.light.borderSecondary};
```suggestion
  border: 1px solid ${colors.light.borderSecondary};
```

2021-02-01 13:02 UTC, emmenko approved these changes

2021-02-01 13:03 UTC, emmenko commented
VRTs approved ✅

2021-02-01 13:56 UTC, merged

2021-02-02 07:57 UTC, Shecki commented
@TimonRey  can we do something about this view?
![image](https://user-images.githubusercontent.com/28807759/106568809-10d48500-6534-11eb-8952-ea7fb8d4d7e8.png)

That it looks like A or B?
![image](https://user-images.githubusercontent.com/28807759/106569370-b687f400-6534-11eb-9000-32756e805cd3.png)

2021-02-02 07:58 UTC, Shecki commented
**Please don't look at the colors here**..
It's just about the form of the background

2021-02-02 08:22 UTC, emmenko commented
Option B is not possible.

Option A also does not really make sense because it's essentially a sentence in a new line.