fix: remove top margin on first content element
commercetools/commercetools-docs-kit pull request #853
Opened 2021-01-28 20:02 UTC by TimonRey

closes #776

2021-01-29 09:16 UTC, emmenko approved these changes
Selector looks good.

I think @Shecki or @nkuehn should check the Percy snapshots and approve them if the outcome is ok.

2021-01-29 10:21 UTC, Shecki commented
from my side its fine, but i can´t approv

2021-01-29 12:17 UTC, nkuehn requested changes
Not as intended yet, you can see in the percy shots that it#s also removing a lot of the spacing on the body content.

2021-01-29 12:17 UTC, nkuehn commented on packages/ui-kit/src/components/markdown.js
> +  section:first-of-type > * {
I think the selector is matching too much.  The requirement is to only match the very first content element on a given page, not any direct descendant of the first section. 

```suggestion
  section:first-of-type > *:first-child {
```

2021-02-01 21:18 UTC, nkuehn approved these changes
Thanks! good to go for this step and the correct way to do it

Only one page - the beta page - has a visual regression that makes obvious that we have no explicit space any more now (in fact, never had).  This situation will be addressed with implementing the extra space for the search bar, which will give all pages a fixed extra spacing between header and body content area independently of the specific header or body content.  

![image](https://user-images.githubusercontent.com/4006139/106518589-6aa86100-64da-11eb-8f9f-c4d6b58a7a20.png)

2021-02-02 08:59 UTC, emmenko approved these changes

2021-02-02 08:59 UTC, merged