Document soft linking urn
commercetools/commercetools-docs-kit pull request #998
Opened 2021-06-22 15:22 UTC by davifantasia

2021-07-20 08:13 UTC, timonrey approved these changes
lgtm

2021-07-22 08:48 UTC, nkuehn requested changes
The examples and test cases do not represent what the feature is intended for.  

The point of URN linking is not to have a worse way of hardwiring on what page a given endpoint or type is documented in.  The point of the feature is to be able to link to a type or endpoint without knowing on what page it is.

2021-07-22 08:48 UTC, nkuehn commented on api-specs/test/types/links.raml
> +      Link [ArrayTestType](/types/general#ctp:test:type:ArrayTestType) with `[ArrayTestType](/types/general#ctp:test:type:ArrayTestType)`
This is not a link notation that we should use.   Use either URLs to headings or pure URNs.

2021-07-22 08:48 UTC, nkuehn commented on api-specs/test/types/links.raml
> +          From property description, link [GET request for /{projectKey}/resource/key={key}](/endpoints/methods#ctp:test:endpoint:/%257BprojectKey%257D/resource/key=%257Bkey%257D:GET) with `[GET requ
Same here, this combination does not make sense

2021-07-22 08:48 UTC, nkuehn commented on api-specs/test/types/links.raml
> +          Link using microsite notation with `[Text](/../<microsite-name>/path#ctp:<api-name>:type:<type-name>)`
and again

2021-07-22 08:48 UTC, nkuehn commented on packages/gatsby-theme-api-docs/README.md
> +- Using absolute URL: `[Text](https://example.com/path#ctp:<api-key>:type:<type-name>)`
Also here.

2021-07-22 08:48 UTC, nkuehn commented on packages/gatsby-theme-api-docs/README.md
> +For endpoints, the links are generated using our custom URN - `ctp:<api-key>:endpoint:<end-point>:<method>`. Note that `<end-point>` should includes URI encoded characters for `{`, `}`, `#`, `:`, etc
```suggestion
For endpoints, the links are generated using our custom URN - `ctp:<api-key>:endpoint:<endpoint>:<method>`. Note that `<endpoint>` should includes URI encoded characters for `{`, `}`, `#`, `:`, etc.
```

2021-07-22 08:48 UTC, nkuehn commented on packages/gatsby-theme-api-docs/src/components/resource/method/method.js
> +        <span id={id} />
This causes a confusing merge conflict, but it's actually not a complex change

2021-07-27 15:36 UTC, closed without merging